---
title: "Revisiting species and areas of interest for conserving global mammalian phylogenetic diversity"
author: Github repository & scripts created by Marine Robuchon, with contributions of Boris Leroy, Sandrine Pavoine & Simon Véron
output: 
  # html_document: 
  #   theme: united
  #   toc: true
  #   toc_float: false
  github_document:
    toc: true
    toc_depth: 3
---

## 1. Description & organisation of the repository
The purpose of this github repository is to document the data used, the analyses carried out and the figures and tables produced with RStudio for the paper "Re-identifying species and areas of interest to conserve global mammalian phylogenetic diversity". The repository contains 5 folders (data, images, requireddata, scripts, outputs), which content is described below.

### 1.1. data
This folder includes the following files:

+ pext_Mooers2008.csv (file containing the equivalence between IUCN status and probabilities of extinction according to the model of Mooers et al. 2008)
+ assessments_mammals_25092019.csv (file containing global assessments for mammal species in IUCN version 2019-2)
+ ne_50m_coastline.shp, .shx, .prj, .dbf, .cpg (spatial files for the coastline from Natural Earth https://www.naturalearthdata.com/downloads/50m-physical-vectors/)
+ percentage_pa_grid_raster.tif (raster containing the percentage of area covered by the re-processed and transformed WDPA dataset for each grid cell of the reference gridded map)
+ animal_species_Union-concern.csv (the list of invasive animal species of Union concern, copied from https://ec.europa.eu/environment/nature/invasivealien/list/index_en.htm).

### 1.2. images
This folder includes the following subfolders:

+ raw (folder containing the original images used in the figures, together with a table listing the source and credit for each image)
+ top10hedge (folder containing transformed images of the TOP 10 HEDGE species)
+ top10ledge (folder containing transformed images of the TOP 10 LEDGE species)
+ introduced (folder containing transformed images of some species of interest that are also introduced).

### 1.3. requireddata (only on your computer)
This folder contains data too heavy to be stored in the online github repository, so you will have to create it on your computer and download data yourself (see section "Requirements" below). Once this is done, this folder should include the following files and folders:

+ Complete_phylogeny.nex (file containing phylogenetic trees from PHYLACINE)
+ Trait_data.csv (file containing trait data from PHYLACINE)
+ Current (folder containing species range maps from PHYLACINE)
+ MAMMALS.shp, .shx, .sbx, .sbn, .prj, .dbf, .cpg (shapefiles of mammal species distributions from IUCN)
+ Completed_5911sp_topoCons_NDexp (folder containing phylogenetic trees from Upham et al. 2019)

### 1.4. scripts
This folder includes the following scripts:

+ calc_species_scores.R (script to calculate HEDGE, LEDGE and ED scores)
+ new_functions.R (script containing all new functions created for the analyses)
+ checkphyloarg.R (function to check the arguments of a phylo object)
+ calc_cells_scores.R (script to calculate all spatial scores for each cell of the reference gridded map)
+ calc_PE.R (function to calculate phylogenetic-weighted rarity, slightly modified from https://github.com/DanRosauer/phylospatial/tree/master/PhyloEndemism_in_R)
+ figures_tables.R (script to generate all figures and tables of the paper).

### 1.5. outputs
This folder contains the outputs of the analyses and you should be able to generate them yourself. They are however included here in case you do not manage to generate them yourself. They include the following files:

+ mammals_range_table.csv (file containing the range size calculated for mammal species)
+ Trait_data_status_imputed.csv (file containing trait data plus imputed status)
+ scores_Mammals_median-over-the-100-resolved-trees.csv (file containing median HEDGE, LEDGE and HED scores over the 100 PHYLACINE trees)
+ phylori_Mammals_median-over-the-100-resolved-trees.csv (file containing median scores of phylogenetic originality over the 100 PHYLACINE trees)
+ mammals25092019.csv (file containing all scores and traits together with a comparison of species names between Phylacine and IUCN 2019-2)
+ mammalsTOP25percenthedge.csv (file containing all scores and traits for the TOP 25% HEDGE)
+ mammalsTOP25percentledge.csv (file containing all scores and traits for the TOP 25% LEDGE)
+ mammals_tophedge_conservation_introduction.csv (file listing conservation measures and introduction status - in addition to all scores and traits - for the TOP 25% HEDGE)
+ mammals_topledge_conservation_introduction.csv (file listing conservation measures and introduction status - in addition to all scores and traits - for the TOP 25% LEDGE)
+ scores_Mammals_median-over-the-100-resolved-trees_UPHAM.csv (file containing median HEDGE, LEDGE and HED scores over the 100 UPHAM trees)
+ Map_mammals_richness.grd, .gri (gridded map of species richness)
+ Map_mammals_threatened-richness.grd, .gri (gridded map of threatened species richness)
+ Map_mammals_rare-richness.grd, .gri (gridded map of rare species richness)
+ gridded.presab (dataframe containing the presence-absence of the species for each cell of the reference gridded map)
+ Map_mammals_weighted-rarity.grd, .gri (gridded map of species-weighted rarity)
+ Map_mammals_median-PD.grd, .gri (gridded map of median phylogenetic diversity over 100 trees)
+ Map_mammals_median-threatened-PD.grd, .gri (gridded map of median threatened phylogenetic diversity over 100 trees)
+ Map_mammals_median-rare-PD.grd, .gri (gridded map of median rare phylogenetic diversity over 100 trees)
+ Map_mammals_median-PWR.grd, .gri (gridded map of median phylogenetic-weighted rarity over 100 trees)
+ Map_mammals_richnessTOPHEDGE.grd, .gri (gridded map of the number of species in the TOP 25% HEDGE)
+ Map_mammals_richnessTOPLEDGE.grd, .gri (gridded map of the number of species in the TOP 25% LEDGE)
+ 100 files named with the pattern GexpPD_p0_treei, with i going from 1 to 100 (expected gain in PD if all species present in a grid cell were secured for each of the 100 trees)
+ Map_mammals_median-GexpPD-p0.grd, .gri (gridded map of median expected gain in PD if all species present in a grid cell were secured over 100 trees)
+ Map_mammals_GexpPD_hotspots.grd, .gri (raster of priority areas = the 2.5% cells with the highest expected gain in PD if all species present in a grid cell were secured)
+ 100 files named with the pattern LexpPD_p1_treei, with i going from 1 to 100 (expected loss in PD if all species present in a grid cell became extinct for each of the 100 trees)
+ Map_mammals_median-LexpPD-p1.grd, .gri (gridded map of median expected loss in PD if all species present in a grid cell became extinct over 100 trees)
+ Map_mammals_LexpPD_hotspots.grd (raster of loss-significant areas = the 2.5% cells with the highest expected loss in PD if all species present in a grid cell became extinct)
+ Map_mammals_prop-richness-threatened.grd, .gri (gridded map of the proportion of threatened species)
+ Map_mammals_prop-richness-rare.grd, .gri (gridded map of the proportion of rare species)
+ Map_mammals_mean-weighted-rarity.grd, .gri (gridded map of mean species-weighted rarity)
+ Map_mammals_prop-threatened-PD.grd, .gri (gridded map of the proportion of threatened PD)
+ Map_mammals_prop-rare-PD.grd, .gri (gridded map of the proportion of rare PD)
+ Map_mammals_mean-PWR.grd, .gri (gridded map of mean phylogenetic-weighted rarity)
+ Map_mammals_prop-richness-TOPHEDGE.grd, .gri (gridded map of the proportion of TOP 25% HEDGE species)
+ Map_mammals_prop-richness-TOPLEDGE.grd, .gri (gridded map of the proportion of TOP 25% LEDGE species)
+ tableS1.csv (Table S1 of the paper)
+ fig2.png (Figure 2 of the paper)
+ figS4.png (Figure S4 of the paper)
+ tableS2.csv (Table S2 of the paper)
+ tableS4.csv (Table S4 of the paper)
+ tableS5.csv (Table S5 of the paper)
+ fig5.png (Figure 5 of the paper)
+ fig3.png (Figure 3 of the paper)
+ figS3.png (Figure S3 of the paper)
+ fig4.png (Figure 4 of the paper)
+ figS5.png (Figure S5 of the paper)
+ tableS3.csv (Table S3 of the paper)
+ figS6.png (Figure S6 of the paper)
+ figS7.png (Figure S7 of the paper)
+ fig6.png (Figure 6 of the paper)
+ figS1.png (Figure S1 of the paper)
+ figS2.png (Figure S2 of the paper)

## 2. Requirements
Before starting the analyses, make sure to follow the three requirements described below.

### 2.1. clone repository and create additional folders
Clone this repository in your R working directory on your computer. This will create a folder "consmampd" in your R working directory with 4 folders (data, images, scripts, outputs). Then, in "consmampd", create one additional folder and name it "requireddata".

### 2.2. download data
Go to https://datadryad.org/stash/dataset/doi:10.5061/dryad.bp26v20 and download data. Decompress the downloaded archive folder into the folder "requireddata". Repeat the operation for the .zip file "Current".

Go to https://www.iucnredlist.org/resources/spatial-data-download and download the "Mammals" dataset. Decompress the downloaded archive folder into the folder "requireddata". Note that by doing this, you will access shapefiles of mammal species distributions from the latest available IUCN version, and so it may slightly differ from the 2019-2 version used for the analyses in the paper.

Go to https://data.vertlife.org/, and download the archive "Completed_5911sp_topoCons_NDexp" (under "mammaltree"). Decompress the downloaded archive folder into the folder "requireddata".

### 2.3. install packages
Install the following R packages:

```{r required, eval = FALSE}
install.packages(c("ape", "phylobase", "raster", "redlistr", "rgdal", "adiv", "rredlist", "picante", "phytools", "foreach", "doParallel", "RVAideMemoire", "dplyr", "ggplot2", "RColorBrewer", "tmap", "png", "grid"))
```

## 3. Analyses
Follow the three steps below to reproduce the analyses of the paper.

### 3.1. step 1: calculate species scores and identify species of interest
Run the script "calc_species_scores.R". This will allow you to:

+ calculate the HEDGE, LEDGE and ED scores for species (note that other scores are calculated but not used in the paper)
+ identify the TOP 25% HEDGE species, list the conservation measures they are benefitting and assign them an introduction status
+ identify the TOP 25% LEDGE species, list the conservation measures they are benefitting and assign them an introduction status.

### 3.2. step 2: calculate cells scores and identify areas of interest
Run the script "calc_cells_scores.R". This will allow you to:

+ calculate spatial scores for each cell of the reference gridded map
+ identify the 2.5% cells with the highest expected gain in PD if all species present in a grid cell were secured
+ identify the 2.5% cells with the highest expected loss in PD if all species present in a grid cell became extinct.

### 3.3. step 3: generate figures and tables
Run the script "figures_tables.R". This will allow you to generate all the figures and tables of the paper. Note that, although this script is the backbone to generate the figures and tables of the paper, the final figures and tables appearing in the paper may slightly differ from those generated with this script because of customizations out of R. 


